### ISSUE TITLE
Error running on Synology DSM 6.0 python 2.6

### ISSUE THREAD

**Issue by decon89** [XanderStrike/GazelleUI#25]
Hi,

I don't know much about python on Synology DSM NAS machines. I use python 2.7, but after installing ApolloUI I get this error:
No DB found, creating...
 * Running on http://0.0.0.0:2020/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "ApolloUI.py", line 31, in <module>
    scheduler.init_app(app)
  File "/usr/lib/python2.7/site-packages/flask_apscheduler/scheduler.py", line 6                       8, in init_app
    self.__load_jobs()
  File "/usr/lib/python2.7/site-packages/flask_apscheduler/scheduler.py", line 2                       31, in __load_jobs
    self.add_job(**job)
  File "/usr/lib/python2.7/site-packages/flask_apscheduler/scheduler.py", line 1                       08, in add_job
    return self.__scheduler.add_job(**job_def)
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 4                       11, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 9                       05, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 8                       90, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/lib/python2.7/site-packages/apscheduler/triggers/interval.py", line                        37, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/lib/python2.7/site-packages/apscheduler/util.py", line 83, in astim                       ezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must expli                       citly specify the name of the local timezone. Please refrain from using timezone                       s like EST to prevent problems with daylight saving time. Instead, use a locale                        based timezone name (such as Europe/Helsinki).

And I'm unable to connect on 2020

**Comment by XanderStrike** [comment]
Hmm haven't heard this one before. Does the NAS have a setting for timezone somewhere in its control panel? I suppose you could look into setting the timezone for whatever flavor of linux it runs but I don't really know.

**Comment by bamtan** [comment]
Have you got this to work? I'm interested in installing this on my Synology DS216j too.

**Comment by XanderStrike** [comment]
Unfortunately I don't have a Synology to test on, so I won't be of much help. I can leave the issue open in case @decon89 has a solution.

**Comment by bamtan** [comment]
@XanderStrike what sort of testing would you require? I'd be happy to work with you and try and get this working.

**Comment by decon89** [comment]
Hi, 
Still have no idea how I should fix this, so no, haven't found a workaround.

**Comment by bamtan** [comment]
@XanderStrike 

I've opened an issue on Synocommunity, here: https://github.com/SynoCommunity/spksrc/issues/2637

**Comment by cytec** [comment]
I'm gonna post this here to:

This isn't really an error with GazelleUI but a timezone issue...
Synology sometimes tends to report the timezone as `local` which isn't handled by apscheduler and produces the Error you see, see: https://github.com/agronholm/apscheduler/blob/master/apscheduler/util.py#L82-L87

What might help: 
1. Try set your Timezone in DSM to GMT+0 and try starting the package if that works you should be able to restore the Timezone to the original value
2. Ask upstream (GazelleUI) to implement some kind of "catch" for this or the ability to set a timezone in config manually...

maybe you'll have some luck and @XanderStrike fixes that for you ;)
isn't that hard, belive i did this for one of my own packages a while ago

**Comment by cytec** [comment]
Update: well i've gave this a quick look and it seems like you'll have 2 options here: 

1. It seems like flask-apscheduler supports setting a custom timezone see: https://github.com/viniciuschiele/flask-apscheduler/blob/master/flask_apscheduler/scheduler.py#L247-L249
2. It seems like flask-apscheduler allows you to pass an scheduler to it, and if none given it falls back to the Default BackgroundSheduler...

so either just setting the `SCHEDULER_TIMEZONE`  config option to something that'll work:
```
# Configure Scheduler
class Config(object):
    JOBS = jobs.job_list()
    SCHEDULER_VIEWS_ENABLED = True
    SCHEDULER_TIMEZONE = "Europe/Helsinki"
    DEBUG = True
```
or provide a custom scheduler like this should work too:

```
from apscheduler.schedulers.background import BackgroundScheduler

if os.environ.get('WERKZEUG_RUN_MAIN') == 'true':
  scheduler = APScheduler(scheduler=BackgroundScheduler(timezone="Europe/Helsinki"))
  scheduler.init_app(app)
  scheduler.start()
```

I'd go with the first approach and try to determine the Timezone automatically, if it fails OR returns `local` i'd just go with some UTC value as default

**Comment by XanderStrike** [comment]
Thanks so much for digging into this @cytec, I've created #27 which implements your first suggestion. Since the job just runs every 10 seconds it's not necessary for the timezone to reflect the user's local timezone.

@bamtan would you be willing to check out the branch (`git fetch; git checkout SynologyFix`) and see if it'll run?

**Comment by cytec** [comment]
@XanderStrike no problem ;)
got a few minutes left and checked it:

```
$ ./env/bin/python GazelleUI.py
No DB found, creating...
 * Running on http://0.0.0.0:2020/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 250-271-085
```
Looks good to me ;)

**Comment by XanderStrike** [comment]
Awesome! Thanks all of you guys you've been a huge help. I'll merge now.
